# Generated by Django 3.0.5 on 2020-07-08 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='weightmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='files/pdfs/')),
                ('weight', models.CharField(max_length=100)),
                ('rank', models.CharField(default='', editable=False, max_length=100)),
                ('label', models.CharField(default='', editable=False, max_length=100)),
            ],
            options={
                'db_table': 'weight',
            },
        ),
    ]
